#pragma once

#pragma comment(linker, "/export:DwmAttachMilContent=C:\\Windows\\System32\\dwmapi.DwmAttachMilContent,@111")
#pragma comment(linker, "/export:DwmDefWindowProc=C:\\Windows\\System32\\dwmapi.DwmDefWindowProc,@116")
#pragma comment(linker, "/export:DwmDetachMilContent=C:\\Windows\\System32\\dwmapi.DwmDetachMilContent,@117")
#pragma comment(linker, "/export:DwmEnableBlurBehindWindow=C:\\Windows\\System32\\dwmapi.DwmEnableBlurBehindWindow,@122")
#pragma comment(linker, "/export:DwmEnableComposition=C:\\Windows\\System32\\dwmapi.DwmEnableComposition,@102")
#pragma comment(linker, "/export:DwmEnableMMCSS=C:\\Windows\\System32\\dwmapi.DwmEnableMMCSS,@123")
#pragma comment(linker, "/export:DwmExtendFrameIntoClientArea=C:\\Windows\\System32\\dwmapi.DwmExtendFrameIntoClientArea,@135")
#pragma comment(linker, "/export:DwmFlush=C:\\Windows\\System32\\dwmapi.DwmFlush,@136")
#pragma comment(linker, "/export:DwmGetColorizationColor=C:\\Windows\\System32\\dwmapi.DwmGetColorizationColor,@137")
#pragma comment(linker, "/export:DwmGetCompositionTimingInfo=C:\\Windows\\System32\\dwmapi.DwmGetCompositionTimingInfo,@138")
#pragma comment(linker, "/export:DwmGetGraphicsStreamClient=C:\\Windows\\System32\\dwmapi.DwmGetGraphicsStreamClient,@139")
#pragma comment(linker, "/export:DwmGetGraphicsStreamTransformHint=C:\\Windows\\System32\\dwmapi.DwmGetGraphicsStreamTransformHint,@140")
#pragma comment(linker, "/export:DwmGetTransportAttributes=C:\\Windows\\System32\\dwmapi.DwmGetTransportAttributes,@141")
#pragma comment(linker, "/export:DwmGetWindowAttribute=C:\\Windows\\System32\\dwmapi.DwmGetWindowAttribute,@142")
#pragma comment(linker, "/export:DwmInvalidateIconicBitmaps=C:\\Windows\\System32\\dwmapi.DwmInvalidateIconicBitmaps,@143")
#pragma comment(linker, "/export:DwmIsCompositionEnabled=C:\\Windows\\System32\\dwmapi.DwmIsCompositionEnabled,@144")
#pragma comment(linker, "/export:DwmModifyPreviousDxFrameDuration=C:\\Windows\\System32\\dwmapi.DwmModifyPreviousDxFrameDuration,@145")
#pragma comment(linker, "/export:DwmQueryThumbnailSourceSize=C:\\Windows\\System32\\dwmapi.DwmQueryThumbnailSourceSize,@146")
#pragma comment(linker, "/export:DwmRegisterThumbnail=C:\\Windows\\System32\\dwmapi.DwmRegisterThumbnail,@147")
#pragma comment(linker, "/export:DwmSetDxFrameDuration=C:\\Windows\\System32\\dwmapi.DwmSetDxFrameDuration,@148")
#pragma comment(linker, "/export:DwmSetIconicLivePreviewBitmap=C:\\Windows\\System32\\dwmapi.DwmSetIconicLivePreviewBitmap,@149")
#pragma comment(linker, "/export:DwmSetIconicThumbnail=C:\\Windows\\System32\\dwmapi.DwmSetIconicThumbnail,@150")
#pragma comment(linker, "/export:DwmSetPresentParameters=C:\\Windows\\System32\\dwmapi.DwmSetPresentParameters,@151")
#pragma comment(linker, "/export:DwmSetWindowAttribute=C:\\Windows\\System32\\dwmapi.DwmSetWindowAttribute,@152")
#pragma comment(linker, "/export:DwmUnregisterThumbnail=C:\\Windows\\System32\\dwmapi.DwmUnregisterThumbnail,@153")
#pragma comment(linker, "/export:DwmUpdateThumbnailProperties=C:\\Windows\\System32\\dwmapi.DwmUpdateThumbnailProperties,@154")

#pragma comment(linker, "/export:ord100=C:\\Windows\\System32\\dwmapi.#100,@100,NONAME")
#pragma comment(linker, "/export:ord101=C:\\Windows\\System32\\dwmapi.#101,@101,NONAME")
#pragma comment(linker, "/export:ord103=C:\\Windows\\System32\\dwmapi.#103,@103,NONAME")
#pragma comment(linker, "/export:ord104=C:\\Windows\\System32\\dwmapi.#104,@104,NONAME")
#pragma comment(linker, "/export:ord105=C:\\Windows\\System32\\dwmapi.#105,@105,NONAME")
#pragma comment(linker, "/export:ord106=C:\\Windows\\System32\\dwmapi.#106,@106,NONAME")
#pragma comment(linker, "/export:ord107=C:\\Windows\\System32\\dwmapi.#107,@107,NONAME")
#pragma comment(linker, "/export:ord108=C:\\Windows\\System32\\dwmapi.#108,@108,NONAME")
#pragma comment(linker, "/export:ord109=C:\\Windows\\System32\\dwmapi.#109,@109,NONAME")
#pragma comment(linker, "/export:ord110=C:\\Windows\\System32\\dwmapi.#110,@110,NONAME")
#pragma comment(linker, "/export:ord112=C:\\Windows\\System32\\dwmapi.#112,@112,NONAME")
#pragma comment(linker, "/export:ord113=C:\\Windows\\System32\\dwmapi.#113,@113,NONAME")
#pragma comment(linker, "/export:ord114=C:\\Windows\\System32\\dwmapi.#114,@114,NONAME")
#pragma comment(linker, "/export:ord115=C:\\Windows\\System32\\dwmapi.#115,@115,NONAME")
#pragma comment(linker, "/export:ord118=C:\\Windows\\System32\\dwmapi.#118,@118,NONAME")
#pragma comment(linker, "/export:ord119=C:\\Windows\\System32\\dwmapi.#119,@119,NONAME")
#pragma comment(linker, "/export:ord120=C:\\Windows\\System32\\dwmapi.#120,@120,NONAME")
#pragma comment(linker, "/export:ord121=C:\\Windows\\System32\\dwmapi.#121,@121,NONAME")
#pragma comment(linker, "/export:ord125=C:\\Windows\\System32\\dwmapi.#125,@125,NONAME")
#pragma comment(linker, "/export:ord126=C:\\Windows\\System32\\dwmapi.#126,@126,NONAME")
#pragma comment(linker, "/export:ord127=C:\\Windows\\System32\\dwmapi.#127,@127,NONAME")
#pragma comment(linker, "/export:ord128=C:\\Windows\\System32\\dwmapi.#128,@128,NONAME")
#pragma comment(linker, "/export:ord129=C:\\Windows\\System32\\dwmapi.#129,@129,NONAME")
#pragma comment(linker, "/export:ord130=C:\\Windows\\System32\\dwmapi.#130,@130,NONAME")
#pragma comment(linker, "/export:ord131=C:\\Windows\\System32\\dwmapi.#131,@131,NONAME")
#pragma comment(linker, "/export:ord132=C:\\Windows\\System32\\dwmapi.#132,@132,NONAME")
#pragma comment(linker, "/export:ord133=C:\\Windows\\System32\\dwmapi.#133,@133,NONAME")
#pragma comment(linker, "/export:ord134=C:\\Windows\\System32\\dwmapi.#134,@134,NONAME")
#pragma comment(linker, "/export:ord124=C:\\Windows\\System32\\dwmapi.#124,@124,NONAME")


#define WIN32_LEAN_AND_MEAN             // Exclude rarely-used stuff from Windows headers
// Windows Header Files
#include <windows.h>
